<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clock-module2</name>
   <tag></tag>
   <elementGuidId>f98bee48-df66-413b-93e1-b6b8cbb111bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.container.flip-clock.happy-hours__counter-countdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3c6df4bd-5d8b-45a9-bdae-84199e0c825e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>container flip-clock happy-hours__counter-countdown</value>
      <webElementGuid>415dbf71-a764-4168-b74c-e02752dad576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>00    dni04    (godz)22    (min)14    (sek)</value>
      <webElementGuid>8244db54-91b1-4f17-b43a-e25acbfc3390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/div[@class=&quot;happy-hours&quot;]/div[@class=&quot;happy-hours__counter&quot;]/div[@class=&quot;container flip-clock happy-hours__counter-countdown&quot;]</value>
      <webElementGuid>1f5c080b-b40c-4ce5-a16e-a90ab28e494f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div/div[3]/div</value>
      <webElementGuid>b78592f4-424b-43e0-88b0-84993d9108fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rezerwuj swoje wakacje w najlepszych cenach!'])[1]/following::div[5]</value>
      <webElementGuid>e6021805-b5f0-4cee-b372-a14778c85b11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HAPPYHOURS'])[1]/following::div[5]</value>
      <webElementGuid>e9ff76d7-c2a7-4536-aec9-176161386ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>2de58049-3628-4214-bb6c-cf6e50cc9454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '00    dni04    (godz)22    (min)14    (sek)' or . = '00    dni04    (godz)22    (min)14    (sek)')]</value>
      <webElementGuid>7b06f53e-1cbc-44c3-990a-6605ebcb4d51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
