<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>do-startu-kolejnej-promocji-pozostao</name>
   <tag></tag>
   <elementGuidId>57300ce8-cfe7-4624-8d89-40031436b04b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.happy-hours__counter-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/div/div[3]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>fcba3c30-8405-4dc4-ab9d-ffb76f562f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>happy-hours__counter-text</value>
      <webElementGuid>6326e635-4310-4f37-a25f-957154ac37ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Do startu kolejnej promocji pozostało:
  </value>
      <webElementGuid>2107ad36-58a0-49a1-b6ac-bbae352d5c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/div[@class=&quot;happy-hours&quot;]/div[@class=&quot;happy-hours__counter&quot;]/p[@class=&quot;happy-hours__counter-text&quot;]</value>
      <webElementGuid>00d6a7a4-64bb-411a-a4eb-4a92a1fa287e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div/div[3]/p</value>
      <webElementGuid>4ef8ab44-2f35-44f4-9d03-0c6077bfb688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rezerwuj swoje wakacje w najlepszych cenach!'])[1]/following::p[1]</value>
      <webElementGuid>ba65794e-841a-4a10-abe0-34d8c12a4431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HAPPYHOURS'])[1]/following::p[3]</value>
      <webElementGuid>043ce27c-0467-4d57-8053-c2adea4fb4bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dni'])[1]/preceding::p[1]</value>
      <webElementGuid>089caa1d-23ba-425f-9c97-7b6b1b3761e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(godz)'])[1]/preceding::p[1]</value>
      <webElementGuid>4027c5b0-e750-4fdd-8df9-587ac07f104a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Do startu kolejnej promocji pozostało:']/parent::*</value>
      <webElementGuid>44aabff9-7182-41bf-9462-8a8dd10a625c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p</value>
      <webElementGuid>34bbdbd4-f744-4852-b264-a5673dc9be51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '
    Do startu kolejnej promocji pozostało:
  ' or . = '
    Do startu kolejnej promocji pozostało:
  ')]</value>
      <webElementGuid>23778047-6e67-4c32-9494-409a34633dc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
