<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pokaz-wszystkie-oferty-text</name>
   <tag></tag>
   <elementGuidId>c5554c89-3e62-4468-950b-65bef8ca8b83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/div/div/a/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.happy-hours__top-button > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b801cadf-eca0-49c6-807e-aa6ca4abafc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>pokaż wszystkie oferty</value>
      <webElementGuid>49356554-5756-4ea2-8bb3-1d0e63a63f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/div[@class=&quot;happy-hours&quot;]/div[@class=&quot;happy-hours__top&quot;]/a[@class=&quot;happy-hours__top-button&quot;]/p[1]</value>
      <webElementGuid>b4a2ebbc-eacb-4d01-9012-42c119f0729a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div/div/a/p</value>
      <webElementGuid>1c173013-423e-4a5c-9b05-c754b02a1a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rezerwuj swoje wakacje w najlepszych cenach!'])[1]/following::p[1]</value>
      <webElementGuid>d274dbfe-0d08-45d4-8687-aa4b303f1950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HAPPYHOURS'])[1]/following::p[3]</value>
      <webElementGuid>afb0fde0-3761-4b41-a937-7bd5efeac0c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wypoczynek • Bułgaria: Słoneczny Brzeg - Sozopol'])[1]/preceding::p[2]</value>
      <webElementGuid>86ea7fb8-d307-4693-b0ad-3db1f3c3f968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='inne terminy'])[1]/preceding::p[2]</value>
      <webElementGuid>fa8320bc-0097-470f-9ca4-c26101c9bd99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='pokaż wszystkie oferty']/parent::*</value>
      <webElementGuid>2032a8d8-a9d8-48ee-b022-77d1e58a3586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/p</value>
      <webElementGuid>9ae17661-7df4-435d-8324-76797b146c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'pokaż wszystkie oferty' or . = 'pokaż wszystkie oferty')]</value>
      <webElementGuid>8c90eb2b-6521-4435-b2ed-17aa1c1731a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
