<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pokaz-wszystkie-oferty-link</name>
   <tag></tag>
   <elementGuidId>54b99ca8-f22a-470c-ac1c-6f5d9b3b0cff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.happy-hours__top-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>62213bd4-537a-4643-9ce4-d8b8ea83ce19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>szukaj?promocja=happy-hours</value>
      <webElementGuid>114bef83-0459-43f4-a7c8-29c1e04abb26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>happy-hours__top-button</value>
      <webElementGuid>ce022b2a-8234-4ee9-a146-1c9eec76557a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>pokaż wszystkie oferty</value>
      <webElementGuid>0e9b290e-7469-43e5-9754-fa6912bc77be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/div[@class=&quot;happy-hours&quot;]/div[@class=&quot;happy-hours__top&quot;]/a[@class=&quot;happy-hours__top-button&quot;]</value>
      <webElementGuid>d7599cfb-c234-4422-bec2-904a2294ba64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div/div/a</value>
      <webElementGuid>361489ea-42a3-4fcb-86d4-bc7ce581e81b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rezerwuj swoje wakacje w najlepszych cenach!'])[1]/following::a[1]</value>
      <webElementGuid>1946a148-5728-438f-8ffe-21d7cb2e2a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HAPPYHOURS'])[1]/following::a[1]</value>
      <webElementGuid>001f9265-05fd-4893-be09-7402d6955237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wypoczynek • Bułgaria: Słoneczny Brzeg - Sozopol'])[1]/preceding::a[5]</value>
      <webElementGuid>9e508702-cae4-4820-902b-45626f629e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='inne terminy'])[1]/preceding::a[5]</value>
      <webElementGuid>d6f3e180-7499-48ee-a0c6-32f5efdb7c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'szukaj?promocja=happy-hours')]</value>
      <webElementGuid>9b4a897d-6931-40ed-912c-d621a015c3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>616c7421-5b19-4601-b00a-b83ac93a863f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'szukaj?promocja=happy-hours' and (text() = 'pokaż wszystkie oferty' or . = 'pokaż wszystkie oferty')]</value>
      <webElementGuid>449be5cc-478f-4655-81c8-b3528efc721a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
