<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>content-section__box-3</name>
   <tag></tag>
   <elementGuidId>234d5a18-6008-4d20-bdb6-ae708fbfb501</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/main/section[7]/div/div/div/div/article/section[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>26a75f18-656e-4a8a-a1ff-7c2adbe5cc8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>seo-section__col</value>
      <webElementGuid>dfa5d96f-72fe-4198-95dd-5012a1fcf784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> All InclusiveWyjazdy typu all inclusive są idealnym wyborem dla każdego turysty, zarówno dla singla podróżującego w pojedynkę, dużej rodziny z dziećmi, jak i dla par wybierających się na romantyczną wycieczkę we dwoje. Koszt takich wakacji, choć początkowo może wydawać się wysoki, obejmuje wszelkie wydatki - od podróży, przez pobyt w luksusowym hotelu, po wyżywienie, napoje i drinki. Pamiętaj, że nie ma żadnych międzynarodowych regulacji dokładnie określających, co wchodzi w zakres oferty all inclusive.Niektóre hotele wprowadzają pewne ograniczenia, dlatego szczegóły musisz zawsze sprawdzić przy wyborze konkretnej oferty. Wybierając tę formę urlopu, masz jednak pewność, że nic nie zakłóci Twojego spokoju, nie będziesz musiał zaprzątać sobie głowy żadnymi organizacyjnymi szczegółami. Musisz jedynie wybrać wymarzoną destynację, określić swój budżet i cieszyć się wakacjami.Nasze biuro podróży oferuje wyjazdy all inclusive do miejsc ulubionych przez wielu turystów, które od lat znajdują się w czołówce wybieranych kierunków, takich jak Grecja, Egipt czy Tunezja. Możemy jednak zabrać Cię także w mniej oczywiste miejsca, między innymi do Albanii, Brazylii lub na Malediwy.</value>
      <webElementGuid>4595d0f0-1532-4ded-add0-90539ba0d3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/main[@class=&quot;strona-glowna&quot;]/section[@class=&quot;section section gray&quot;]/div[@class=&quot;wrap&quot;]/div[1]/div[@class=&quot;swiper-r inactive&quot;]/div[@class=&quot;swiper-r__wrap&quot;]/article[@class=&quot;swiper-r__slides seo-section&quot;]/section[@class=&quot;seo-section__col&quot;]</value>
      <webElementGuid>fe5ed505-ee0c-4a9f-98c3-240efa2eacc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/section[7]/div/div/div/div/article/section[3]</value>
      <webElementGuid>4ec75ed3-6930-42f6-80e2-72b677b60460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='wyjazd skrojony na miarę swoich potrzeb'])[1]/following::section[1]</value>
      <webElementGuid>c8579e5e-19dd-494a-9c93-a5b80d6392e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opieka polskiego pilota'])[1]/following::section[1]</value>
      <webElementGuid>cab91c2c-f921-46f5-ad0d-6fbfce00c7c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/section[3]</value>
      <webElementGuid>acfe500a-72d6-4134-9846-f117ef459c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[(text() = ' All InclusiveWyjazdy typu all inclusive są idealnym wyborem dla każdego turysty, zarówno dla singla podróżującego w pojedynkę, dużej rodziny z dziećmi, jak i dla par wybierających się na romantyczną wycieczkę we dwoje. Koszt takich wakacji, choć początkowo może wydawać się wysoki, obejmuje wszelkie wydatki - od podróży, przez pobyt w luksusowym hotelu, po wyżywienie, napoje i drinki. Pamiętaj, że nie ma żadnych międzynarodowych regulacji dokładnie określających, co wchodzi w zakres oferty all inclusive.Niektóre hotele wprowadzają pewne ograniczenia, dlatego szczegóły musisz zawsze sprawdzić przy wyborze konkretnej oferty. Wybierając tę formę urlopu, masz jednak pewność, że nic nie zakłóci Twojego spokoju, nie będziesz musiał zaprzątać sobie głowy żadnymi organizacyjnymi szczegółami. Musisz jedynie wybrać wymarzoną destynację, określić swój budżet i cieszyć się wakacjami.Nasze biuro podróży oferuje wyjazdy all inclusive do miejsc ulubionych przez wielu turystów, które od lat znajdują się w czołówce wybieranych kierunków, takich jak Grecja, Egipt czy Tunezja. Możemy jednak zabrać Cię także w mniej oczywiste miejsca, między innymi do Albanii, Brazylii lub na Malediwy.' or . = ' All InclusiveWyjazdy typu all inclusive są idealnym wyborem dla każdego turysty, zarówno dla singla podróżującego w pojedynkę, dużej rodziny z dziećmi, jak i dla par wybierających się na romantyczną wycieczkę we dwoje. Koszt takich wakacji, choć początkowo może wydawać się wysoki, obejmuje wszelkie wydatki - od podróży, przez pobyt w luksusowym hotelu, po wyżywienie, napoje i drinki. Pamiętaj, że nie ma żadnych międzynarodowych regulacji dokładnie określających, co wchodzi w zakres oferty all inclusive.Niektóre hotele wprowadzają pewne ograniczenia, dlatego szczegóły musisz zawsze sprawdzić przy wyborze konkretnej oferty. Wybierając tę formę urlopu, masz jednak pewność, że nic nie zakłóci Twojego spokoju, nie będziesz musiał zaprzątać sobie głowy żadnymi organizacyjnymi szczegółami. Musisz jedynie wybrać wymarzoną destynację, określić swój budżet i cieszyć się wakacjami.Nasze biuro podróży oferuje wyjazdy all inclusive do miejsc ulubionych przez wielu turystów, które od lat znajdują się w czołówce wybieranych kierunków, takich jak Grecja, Egipt czy Tunezja. Możemy jednak zabrać Cię także w mniej oczywiste miejsca, między innymi do Albanii, Brazylii lub na Malediwy.')]</value>
      <webElementGuid>6916751c-6673-4c56-8722-4bdd324ead70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
