<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>content-section__box-2</name>
   <tag></tag>
   <elementGuidId>ed65d95a-f23d-4cf3-b056-29b71c4dfc17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/main/section[7]/div/div/div/div/article/section[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>10bfada3-4201-4fda-9c02-af506ad321dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>seo-section__col</value>
      <webElementGuid>ce7fe0ec-7d8c-4e8d-9317-ffba2039dcd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wycieczki objazdoweLubisz poznawać nowe miejsca, podczas każdej podróży musisz zobaczyć wszystkie lokalne zabytki i ciekawostki, a siedzenie zbyt długo w jednym miejscu zwyczajnie Cię nudzi? Jeśli lubisz zwiedzać i często zmieniać otoczenie, to wczasy typy all-inclusive z pewnością nie mieszczą się w Twojej definicji udanego urlopu. Mamy jednak coś, co może Cię zainteresować, ponieważ nasze biuro podróży organizuje wycieczki objazdowe do wielu ciekawych miejsc.Z nami możesz odwiedzić Budapeszt i Zamki Siedmiogrodu, wybrać się do Rumunii szlakiem hrabiego Drakuli lub wyruszyć na Dalmatyńską Eskapadę do Chorwacji i Słowenii. W swojej ofercie mamy także wycieczki objazdowe dla wygodnych, podczas których przewidzianych jest więcej noclegów, grupy są mniejsze, a plan zwiedzania – mniej napięty. Opieka polskiego pilota, który jest świetnie zorientowany w lokalnych realiach sprawia, że poznajesz zwiedzane kraje „od podszewki”, masz szansę zobaczyć to, o czym nie piszą w przewodnikach.Niezależnie od tego, czy wolisz włóczyć się po starych zamczyskach, relaksować się w parkach rozrywki czy poznawać kulturę i folklor odwiedzanych państw, u nas z pewnością znajdziesz wyjazd skrojony na miarę swoich potrzeb.</value>
      <webElementGuid>98d52fb6-00f0-456b-91fa-409b225aaa8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/main[@class=&quot;strona-glowna&quot;]/section[@class=&quot;section section gray&quot;]/div[@class=&quot;wrap&quot;]/div[1]/div[@class=&quot;swiper-r inactive&quot;]/div[@class=&quot;swiper-r__wrap&quot;]/article[@class=&quot;swiper-r__slides seo-section&quot;]/section[@class=&quot;seo-section__col&quot;]</value>
      <webElementGuid>9537d86e-9a73-45c2-9cb9-345f4361cc25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/section[7]/div/div/div/div/article/section[2]</value>
      <webElementGuid>e2c69078-ac2b-4085-bdff-4df1b60ada2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pyszne, lokalne jedzenie'])[1]/following::section[1]</value>
      <webElementGuid>8f2f0e94-d488-4fd9-af43-3668aec557e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chorwacja, Grecja lub Portugalia'])[1]/following::section[1]</value>
      <webElementGuid>46acc385-045b-4b91-ae7e-955d495af5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/section[2]</value>
      <webElementGuid>69f167f5-b52f-40a8-888d-b13891a270ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[(text() = 'Wycieczki objazdoweLubisz poznawać nowe miejsca, podczas każdej podróży musisz zobaczyć wszystkie lokalne zabytki i ciekawostki, a siedzenie zbyt długo w jednym miejscu zwyczajnie Cię nudzi? Jeśli lubisz zwiedzać i często zmieniać otoczenie, to wczasy typy all-inclusive z pewnością nie mieszczą się w Twojej definicji udanego urlopu. Mamy jednak coś, co może Cię zainteresować, ponieważ nasze biuro podróży organizuje wycieczki objazdowe do wielu ciekawych miejsc.Z nami możesz odwiedzić Budapeszt i Zamki Siedmiogrodu, wybrać się do Rumunii szlakiem hrabiego Drakuli lub wyruszyć na Dalmatyńską Eskapadę do Chorwacji i Słowenii. W swojej ofercie mamy także wycieczki objazdowe dla wygodnych, podczas których przewidzianych jest więcej noclegów, grupy są mniejsze, a plan zwiedzania – mniej napięty. Opieka polskiego pilota, który jest świetnie zorientowany w lokalnych realiach sprawia, że poznajesz zwiedzane kraje „od podszewki”, masz szansę zobaczyć to, o czym nie piszą w przewodnikach.Niezależnie od tego, czy wolisz włóczyć się po starych zamczyskach, relaksować się w parkach rozrywki czy poznawać kulturę i folklor odwiedzanych państw, u nas z pewnością znajdziesz wyjazd skrojony na miarę swoich potrzeb.' or . = 'Wycieczki objazdoweLubisz poznawać nowe miejsca, podczas każdej podróży musisz zobaczyć wszystkie lokalne zabytki i ciekawostki, a siedzenie zbyt długo w jednym miejscu zwyczajnie Cię nudzi? Jeśli lubisz zwiedzać i często zmieniać otoczenie, to wczasy typy all-inclusive z pewnością nie mieszczą się w Twojej definicji udanego urlopu. Mamy jednak coś, co może Cię zainteresować, ponieważ nasze biuro podróży organizuje wycieczki objazdowe do wielu ciekawych miejsc.Z nami możesz odwiedzić Budapeszt i Zamki Siedmiogrodu, wybrać się do Rumunii szlakiem hrabiego Drakuli lub wyruszyć na Dalmatyńską Eskapadę do Chorwacji i Słowenii. W swojej ofercie mamy także wycieczki objazdowe dla wygodnych, podczas których przewidzianych jest więcej noclegów, grupy są mniejsze, a plan zwiedzania – mniej napięty. Opieka polskiego pilota, który jest świetnie zorientowany w lokalnych realiach sprawia, że poznajesz zwiedzane kraje „od podszewki”, masz szansę zobaczyć to, o czym nie piszą w przewodnikach.Niezależnie od tego, czy wolisz włóczyć się po starych zamczyskach, relaksować się w parkach rozrywki czy poznawać kulturę i folklor odwiedzanych państw, u nas z pewnością znajdziesz wyjazd skrojony na miarę swoich potrzeb.')]</value>
      <webElementGuid>cab60de8-894c-46c7-8335-e067fc8b6ea9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
