<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>content-section__span-Ukryj</name>
   <tag></tag>
   <elementGuidId>0fcde435-e37a-4038-b373-165b2366b720</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/main/section[7]/div/div/div[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.seo-szukaj__pokaz-wiecej > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>316aab43-2cf2-43a1-96d7-eec603b99e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ukryj</value>
      <webElementGuid>5ecd1571-9b30-4e25-b5bc-3961b43d781e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/main[@class=&quot;strona-glowna&quot;]/section[@class=&quot;section section gray&quot;]/div[@class=&quot;wrap&quot;]/div[1]/div[@class=&quot;seo-szukaj__pokaz-wiecej&quot;]/span[1]</value>
      <webElementGuid>2c9edf80-7951-4ad2-bff3-5368c1ed926f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/section[7]/div/div/div[3]/span</value>
      <webElementGuid>b84c7d2f-09e4-4036-aa43-25c767c18322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='biuro podróży'])[2]/following::span[1]</value>
      <webElementGuid>8a42be5f-1e0c-4548-a710-af548c2e64ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Inclusive'])[1]/following::span[1]</value>
      <webElementGuid>25a95d9f-acaf-4883-9ee2-07b295359532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Call center'])[1]/preceding::span[1]</value>
      <webElementGuid>cc94e300-16a9-4463-9893-55514392d6ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mail'])[1]/preceding::span[2]</value>
      <webElementGuid>9d06b1d6-367b-457f-a070-5187a129ed2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ukryj']/parent::*</value>
      <webElementGuid>75da5e8d-0bca-419f-8748-abc62fc28d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[6]/div/div/div[3]/span</value>
      <webElementGuid>3b35ee04-707c-4a78-bc4d-4fd1182ab4f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Ukryj' or . = 'Ukryj')]</value>
      <webElementGuid>7449424e-89b8-4fbb-a955-a319323252ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
