<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>content-section__box-1</name>
   <tag></tag>
   <elementGuidId>ec882b74-0685-401f-9599-3c07cd67466e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/main/section[6]/div/div/div/div/article/section</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>section.seo-section__col</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>e4bdb6e8-8531-4585-89c7-c42716951145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>seo-section__col</value>
      <webElementGuid>803d8934-3e7e-4a94-86a5-0493fa635e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Last minuteJesteś ostatnio przemęczony i nie możesz się skupić na pracy, a aura za oknem sprawia, że najchętniej przez cały dzień nie wychodziłbyś spod kołdry? Zamiast zastanawiać się, jak przetrwać i nie zwariować sprawdź jaką ofertę last minute przygotowało nasze biuro podróży!Jeśli tylko możesz na kilka dni oderwać się od obowiązków, to teraz jest najlepszy czas na podróż, ponieważ mamy wiele ciekawych destynacji w bardzo atrakcyjnych cenach. Może zainteresuje Cię Chorwacja, Grecja lub Portugalia? Tam zawsze masz gwarancję dobrej pogody, a niezliczone atrakcje turystyczne sprawią, że każdy dzień pobytu będzie pełen wrażeń. Dodaj do tego pyszne, lokalne jedzenie i otrzymasz definicję idealnego urlopu.Oferta last minute jest świetnym rozwiązaniem dla osób podchodzących do życia spontanicznie, które nie lubią tworzyć długoterminowych planów.Czasami wystarczy tylko spakować kilka najpotrzebniejszych rzeczy i wyruszyć w podróż, która może stać się przygodą życia. Udany urlop wcale nie wymaga od Ciebie wielu miesięcy poszukiwań i zastanawiania się, gdzie i kiedy wyjechać. Od dawna marzysz o wyjeździe do Izraela czy Gruzji, ale zawsze się martwisz o finanse? Sprawdź naszą ofertę, bo teraz wyśnione wakacje są na wyciągnięcie ręki!</value>
      <webElementGuid>e91af1fa-dbf1-40cf-b611-592c035f8492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/main[@class=&quot;strona-glowna&quot;]/section[@class=&quot;section section gray&quot;]/div[@class=&quot;wrap&quot;]/div[1]/div[@class=&quot;swiper-r inactive&quot;]/div[@class=&quot;swiper-r__wrap&quot;]/article[@class=&quot;swiper-r__slides seo-section&quot;]/section[@class=&quot;seo-section__col&quot;]</value>
      <webElementGuid>4e1d599d-79e2-4103-9f84-4024b7622fbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/section[6]/div/div/div/div/article/section</value>
      <webElementGuid>957eb46d-9893-4013-94bf-b8a78ff18aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pogoda, klimat i średnie temperatury w Hiszpanii'])[1]/following::section[2]</value>
      <webElementGuid>5febe876-9afc-48a0-b513-cebb0c515a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pogoda, klimat i temperatury w Portugalii. Kiedy jechać do Lizbony i Algarve?'])[1]/following::section[2]</value>
      <webElementGuid>cd186bb8-208c-48e6-9442-12717cccb346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/section</value>
      <webElementGuid>611e1fc6-9848-45e3-8fde-c203efee8c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[(text() = 'Last minuteJesteś ostatnio przemęczony i nie możesz się skupić na pracy, a aura za oknem sprawia, że najchętniej przez cały dzień nie wychodziłbyś spod kołdry? Zamiast zastanawiać się, jak przetrwać i nie zwariować sprawdź jaką ofertę last minute przygotowało nasze biuro podróży!Jeśli tylko możesz na kilka dni oderwać się od obowiązków, to teraz jest najlepszy czas na podróż, ponieważ mamy wiele ciekawych destynacji w bardzo atrakcyjnych cenach. Może zainteresuje Cię Chorwacja, Grecja lub Portugalia? Tam zawsze masz gwarancję dobrej pogody, a niezliczone atrakcje turystyczne sprawią, że każdy dzień pobytu będzie pełen wrażeń. Dodaj do tego pyszne, lokalne jedzenie i otrzymasz definicję idealnego urlopu.Oferta last minute jest świetnym rozwiązaniem dla osób podchodzących do życia spontanicznie, które nie lubią tworzyć długoterminowych planów.Czasami wystarczy tylko spakować kilka najpotrzebniejszych rzeczy i wyruszyć w podróż, która może stać się przygodą życia. Udany urlop wcale nie wymaga od Ciebie wielu miesięcy poszukiwań i zastanawiania się, gdzie i kiedy wyjechać. Od dawna marzysz o wyjeździe do Izraela czy Gruzji, ale zawsze się martwisz o finanse? Sprawdź naszą ofertę, bo teraz wyśnione wakacje są na wyciągnięcie ręki!' or . = 'Last minuteJesteś ostatnio przemęczony i nie możesz się skupić na pracy, a aura za oknem sprawia, że najchętniej przez cały dzień nie wychodziłbyś spod kołdry? Zamiast zastanawiać się, jak przetrwać i nie zwariować sprawdź jaką ofertę last minute przygotowało nasze biuro podróży!Jeśli tylko możesz na kilka dni oderwać się od obowiązków, to teraz jest najlepszy czas na podróż, ponieważ mamy wiele ciekawych destynacji w bardzo atrakcyjnych cenach. Może zainteresuje Cię Chorwacja, Grecja lub Portugalia? Tam zawsze masz gwarancję dobrej pogody, a niezliczone atrakcje turystyczne sprawią, że każdy dzień pobytu będzie pełen wrażeń. Dodaj do tego pyszne, lokalne jedzenie i otrzymasz definicję idealnego urlopu.Oferta last minute jest świetnym rozwiązaniem dla osób podchodzących do życia spontanicznie, które nie lubią tworzyć długoterminowych planów.Czasami wystarczy tylko spakować kilka najpotrzebniejszych rzeczy i wyruszyć w podróż, która może stać się przygodą życia. Udany urlop wcale nie wymaga od Ciebie wielu miesięcy poszukiwań i zastanawiania się, gdzie i kiedy wyjechać. Od dawna marzysz o wyjeździe do Izraela czy Gruzji, ale zawsze się martwisz o finanse? Sprawdź naszą ofertę, bo teraz wyśnione wakacje są na wyciągnięcie ręki!')]</value>
      <webElementGuid>a57cb491-fc40-4959-b245-f9ab589da0e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
