<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchBar-szukaj-btn</name>
   <tag></tag>
   <elementGuidId>c56a278c-0ce2-4896-84c4-878159f3d5be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/main/header/div/div/div[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.filtry__search.r-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>49b2f9ae-0835-4454-9a8b-61c57a644dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/szukaj</value>
      <webElementGuid>a882119a-3222-4e86-a757-4c0a0bcf6ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Szukaj</value>
      <webElementGuid>6ab9e890-f2e2-4cb5-81bb-33791ec927af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filtry__search r-button</value>
      <webElementGuid>db9e16d4-fd00-49a1-88c2-7a1f0f03aa5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      SZUKAJ
    </value>
      <webElementGuid>42222ee3-eea0-4cde-b1fc-80ff229d22f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/main[@class=&quot;strona-glowna&quot;]/header[@class=&quot;header-banner header-banner__webp&quot;]/div[@class=&quot;wrap wrap-header&quot;]/div[@class=&quot;filtry filtry&quot;]/div[@class=&quot;filtry__element filtry__element--search&quot;]/a[@class=&quot;filtry__search r-button&quot;]</value>
      <webElementGuid>9a48ce99-4e01-429d-bba1-6f7fa636308a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/header/div/div/div[6]/a</value>
      <webElementGuid>897c245f-e04e-423c-9943-1cc232dcfee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SZUKAJ')]</value>
      <webElementGuid>c6e81a08-77b5-4c29-b375-08af327508b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Samolot'])[1]/following::a[1]</value>
      <webElementGuid>2c64646f-93a8-4c36-81e7-e93d375c8b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Typ Transportu'])[1]/following::a[1]</value>
      <webElementGuid>b2ed26b0-1358-4300-8f2e-e987bbc0c33f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biuro podróży Rainbow'])[1]/preceding::a[1]</value>
      <webElementGuid>2a1f7549-16f1-4bad-a73e-a572811c94ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Objazd + wypoczynek • Kuba: Varadero'])[1]/preceding::a[4]</value>
      <webElementGuid>83d83fc5-73f0-42bc-84ad-dfe57476e2d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SZUKAJ']/parent::*</value>
      <webElementGuid>41b4eb4e-5920-4461-8bf1-9ad0c5e8a868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/szukaj')]</value>
      <webElementGuid>e83eefee-4428-409f-b4df-7c3dfb5a062c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[6]/a</value>
      <webElementGuid>24339e3e-da63-40cf-a055-c30472202f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/szukaj' and @title = 'Szukaj' and (text() = '
      SZUKAJ
    ' or . = '
      SZUKAJ
    ')]</value>
      <webElementGuid>c9224610-5c82-45b3-8ca4-b4a4f281f5d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
