<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Check query for search bar filters</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>e268687f-b096-488e-a2b1-821705864ec6</testSuiteGuid>
   <testCaseLink>
      <guid>3a97b340-842a-42ae-a5b3-7b30e8249abc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Desktop Tests/SearchPage/units-search-bar/search-bar-cities</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53936cb6-25ee-40a1-bc6d-2889b95c4ea0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9e1a9a6-a39e-4d76-b047-ba425db7bdf3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4aeb352-1fcd-434c-9add-0adbd2613094</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Desktop Tests/SearchPage/units-search-bar/search-bar-transportation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4fcd093-0475-48a9-bbdd-a921d6d8df4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a0840f2-242b-47b3-a528-3fec2c790918</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
