<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Homepage Basic Tests</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>2</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>0fbc1ed6-79b6-444a-b3e5-33cb74e79c0c</testSuiteGuid>
   <testCaseLink>
      <guid>b2e5c0da-15ac-476e-ae8f-6b0df5f21fc0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Homepage/homepage-basic-test</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9f9e785-b74f-4dea-9a06-f9260e594fa4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>778bf2fa-d5e5-447c-b86f-462ae4ca0b53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cf9aec9-bfca-4b3b-b49c-6722a83874dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbbaa01c-0124-4780-a9d2-9a15449a574e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6ecb183-deac-4dc8-b121-f62178677bb1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9877fb8f-9064-458b-8416-ef5c62f1487b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Homepage/Nav and footer/Navigation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fca614c7-a22e-4a67-a8a8-d346b28d0db7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>af12132a-2a23-4c80-827d-e38e9b8a0148</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Homepage/Nav and footer/Footer</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58e3a608-b1c5-45a9-aeff-6fa9919122b0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
