<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Zaloguj sie</name>
   <tag></tag>
   <elementGuidId>3f689b13-01ed-4b70-b2a7-51d419c40040</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header__mobile']/div/div[2]/div[2]/div/div/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c5d3dcf1-2466-47f7-8eb7-b2c1ee18c61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://panel-klienta.r.pl</value>
      <webElementGuid>da0ea386-6a0d-4da6-b0c2-69c38199ec47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>footer-men__siteMap__link</value>
      <webElementGuid>0045a87e-5c22-4e66-88c7-410816dd80be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Zaloguj się </value>
      <webElementGuid>8e474445-73ad-447b-9eaf-f092d3b9324c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header__mobile&quot;)/div[1]/div[2]/div[@class=&quot;mobile__menu open&quot;]/div[@class=&quot;mobile__open&quot;]/div[@class=&quot;footer-menu&quot;]/div[@class=&quot;footer-menu-container&quot;]/a[@class=&quot;footer-men__siteMap__link&quot;]</value>
      <webElementGuid>4d7cf395-353b-40ed-8142-f3be203ec3b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header__mobile']/div/div[2]/div[2]/div/div/div/a[2]</value>
      <webElementGuid>50b15a44-47af-40a9-8824-40c5ab6b32fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ulubione'])[1]/following::a[1]</value>
      <webElementGuid>cdbf5893-b426-476e-b208-9834cf52d5bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog'])[1]/following::a[2]</value>
      <webElementGuid>fc1c13e9-fef3-41c0-9b6e-e0411554fa05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Codziennie 8 - 22'])[1]/preceding::a[1]</value>
      <webElementGuid>2af83366-9483-45f9-90b7-b75e0503b4ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://panel-klienta.r.pl')]</value>
      <webElementGuid>9f017f8e-013a-4fed-b295-efe63be32960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a[2]</value>
      <webElementGuid>2aa3978d-77ae-40f4-bc39-02294a79bcd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://panel-klienta.r.pl' and (text() = ' Zaloguj się ' or . = ' Zaloguj się ')]</value>
      <webElementGuid>cb95d850-16cd-4ab8-b2df-0ee32b949a3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
