<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>burger-cross</name>
   <tag></tag>
   <elementGuidId>26b62fdc-4a68-47c4-b661-5034d1f739f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header__mobile']/div/div/img[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.mobile__header-cross</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8c766547-5926-4b21-9704-d47a73649a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//images2.r.pl/r-pl/nowe-menu-gorne/Cross.svg</value>
      <webElementGuid>43a09065-91c5-4a9d-8fb5-e2c99788609a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ikona-x</value>
      <webElementGuid>30e9baa3-9ab2-45e2-ba4e-5233963571c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobile__header-cross</value>
      <webElementGuid>f4dbd2c1-8825-43eb-8bbe-5c438877128e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header__mobile&quot;)/div[1]/div[@class=&quot;mobile__header&quot;]/img[@class=&quot;mobile__header-cross&quot;]</value>
      <webElementGuid>9eabb7f7-f50a-4d62-959f-4902e16b0ebd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header__mobile']/div/div/img[2]</value>
      <webElementGuid>db4a3c48-6583-4810-bf8e-bfa42aec3aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='ikona-x']</value>
      <webElementGuid>acdff997-0534-4c5f-a235-d50177feda8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>242c80b5-d6bd-4663-8d58-06bcab815eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//images2.r.pl/r-pl/nowe-menu-gorne/Cross.svg' and @alt = 'ikona-x']</value>
      <webElementGuid>390296f0-42e3-41da-b02b-795c9908200f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
