<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>burger</name>
   <tag></tag>
   <elementGuidId>991c019e-d1f6-4cd6-94ea-988ae5a8abea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header__mobile']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.mobile__header-burger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fa63cec2-8e25-4e33-98ef-cf7f9e44c8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//images2.r.pl/r-pl/nowe-menu-gorne/Burger.svg</value>
      <webElementGuid>05acb6a7-e58c-4d8c-91ff-0555ce6245a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ikona-burger</value>
      <webElementGuid>42dbec00-567b-409b-a209-f133d74f8488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobile__header-burger</value>
      <webElementGuid>3b1ba2b7-0c38-497f-b9f5-ab7eb3a3d848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header__mobile&quot;)/div[1]/div[@class=&quot;mobile__header&quot;]/img[@class=&quot;mobile__header-burger&quot;]</value>
      <webElementGuid>d509ff98-c7f6-45bd-a51e-5ef5addb1e3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header__mobile']/div/div/img</value>
      <webElementGuid>98a29824-e4e6-4ca1-b869-10dbefc1b645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='ikona-burger']</value>
      <webElementGuid>af26ac0b-615f-43d3-94d6-2e554836b425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>c929063b-f144-4c50-9e03-adc0b9715f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//images2.r.pl/r-pl/nowe-menu-gorne/Burger.svg' and @alt = 'ikona-burger']</value>
      <webElementGuid>45dde714-2327-44d2-a06a-983d7e124ab5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
