<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>info-ukraina</name>
   <tag></tag>
   <elementGuidId>2d75e0a3-3907-4672-a792-eaec8ecdf618</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header__mobile']/div/div/a[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.mobile__header-flag</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>26aa9540-068d-4755-b9a6-54a0d378461d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//images2.r.pl/r-pl/nowe-menu-gorne/flagaUkraina.svg</value>
      <webElementGuid>18cf9396-ab56-4823-8bd1-fc832db4b6ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ikona-Ukraina</value>
      <webElementGuid>23fc9a07-1f8a-4996-bcb6-281730582f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobile__header-flag</value>
      <webElementGuid>f0fcf1e0-5ee7-4757-80be-35a0df5c4a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header__mobile&quot;)/div[1]/div[@class=&quot;mobile__header&quot;]/a[@class=&quot;footer-men__siteMap__link&quot;]/img[@class=&quot;mobile__header-flag&quot;]</value>
      <webElementGuid>7311aa49-7044-4d81-aecf-f62de0c3b98e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header__mobile']/div/div/a[2]/img</value>
      <webElementGuid>faac748e-a1dc-47cc-a9d5-920da0d088a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='ikona-Ukraina']</value>
      <webElementGuid>581d8dc0-842c-4ae7-bcfb-355c8dadbb8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>bea64574-a1f3-4492-9794-d730c986aee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//images2.r.pl/r-pl/nowe-menu-gorne/flagaUkraina.svg' and @alt = 'ikona-Ukraina']</value>
      <webElementGuid>0fb075ff-bdc6-4b7d-9739-633d582969ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
