<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Logo</name>
   <tag></tag>
   <elementGuidId>3431f37f-49cf-4301-a1f7-d59eec8f2e49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header__mobile']/div/div/a/div/figure</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>figure.mobile__header-figure</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>figure</value>
      <webElementGuid>97e4b591-3143-4345-83ef-8cfaeff7a691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobile__header-figure</value>
      <webElementGuid>59cf2b28-5e5b-4172-9862-7b9cb17d6dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header__mobile&quot;)/div[1]/div[@class=&quot;mobile__header&quot;]/a[@class=&quot;footer-men__siteMap__link&quot;]/div[@class=&quot;mobile__header-rpl&quot;]/figure[@class=&quot;mobile__header-figure&quot;]</value>
      <webElementGuid>0a737d92-8c50-43f4-aac8-a13552377242</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header__mobile']/div/div/a/div/figure</value>
      <webElementGuid>6f52327e-ab0c-420d-a4dc-bfcef4641852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokąd chcesz jechać?'])[1]/preceding::figure[1]</value>
      <webElementGuid>5d4b69f9-fba4-412d-8472-3301541afbdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gdziekolwiek'])[1]/preceding::figure[1]</value>
      <webElementGuid>18c97046-080b-4fe9-9193-7b3a7bed83c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure</value>
      <webElementGuid>57db1954-3868-4def-a26b-1e612672f923</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
