<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Oferta-akord</name>
   <tag></tag>
   <elementGuidId>afd621f8-ce89-445d-8b7d-0e0ae78d9fea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header__mobile']/div/div[2]/div[2]/div/nav/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mobile__kategoria__wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3bfb5ccf-b4ab-4534-bd98-5766eff72b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobile__kategoria__wrapper</value>
      <webElementGuid>330b2aa0-b1f2-4204-841b-4efe73c2fd8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Oferta</value>
      <webElementGuid>6794f050-0568-4752-a420-094035c29d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header__mobile&quot;)/div[1]/div[2]/div[@class=&quot;mobile__menu open&quot;]/div[@class=&quot;mobile__open&quot;]/nav[@class=&quot;mobile__kategorie_container&quot;]/div[1]/div[@class=&quot;mobile__kategoria__wrapper&quot;]</value>
      <webElementGuid>6dedcf94-c2f8-4be8-afe8-b35e2230905e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header__mobile']/div/div[2]/div[2]/div/nav/div/div</value>
      <webElementGuid>dd5a5505-6f4e-4152-8932-97027d945fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lato 2022'])[1]/preceding::div[3]</value>
      <webElementGuid>853a7d4c-1b17-41bb-a018-cc48abb93353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div</value>
      <webElementGuid>15ded31e-3d17-4592-8646-cb87f84023f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Oferta' or . = 'Oferta')]</value>
      <webElementGuid>20a0bd98-8e2c-4633-8c71-b8084c802e9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
