<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>phone-img</name>
   <tag></tag>
   <elementGuidId>9e24c939-952a-40af-add3-fd26aac62d14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header__mobile']/div/div/a[3]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.mobile__header-phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>579d9936-5469-4b95-925b-8ffe53a062e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//images2.r.pl/r-pl/nowe-menu-gorne/Phone.svg</value>
      <webElementGuid>97596407-3142-43e2-a61e-b94e41299ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ikona-telefon</value>
      <webElementGuid>31061d60-1386-40e1-8a4a-985442807c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobile__header-phone</value>
      <webElementGuid>f54ab8a4-3523-40bc-b9f2-db6063f1dd0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header__mobile&quot;)/div[1]/div[@class=&quot;mobile__header&quot;]/a[@class=&quot;footer-men__siteMap__link&quot;]/img[@class=&quot;mobile__header-phone&quot;]</value>
      <webElementGuid>2e430900-3cd4-4fe7-95ff-e96b2d36f45b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header__mobile']/div/div/a[3]/img</value>
      <webElementGuid>7f6b268b-26b3-42dd-9983-3ef8e750c523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='ikona-telefon']</value>
      <webElementGuid>b95fbaf8-2a25-48cd-937d-f443c2c030e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/img</value>
      <webElementGuid>bd9b805a-f352-4503-a945-f22ba0ce94c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//images2.r.pl/r-pl/nowe-menu-gorne/Phone.svg' and @alt = 'ikona-telefon']</value>
      <webElementGuid>0db7e13e-b95a-4a80-bad5-6545bafe5047</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
