<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Promocje-akord</name>
   <tag></tag>
   <elementGuidId>7bd9a90c-a067-499e-b97d-c2d3d2cffefc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header__mobile']/div/div[2]/div[2]/div/nav/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b076eca0-d244-4d8b-8ede-6742310a424b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobile__kategoria__wrapper</value>
      <webElementGuid>457f8290-14c7-4ede-9d2d-b14ed1e154c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Promocje</value>
      <webElementGuid>09871114-f513-4ca2-b7b7-cdc7fc1b952e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header__mobile&quot;)/div[1]/div[2]/div[@class=&quot;mobile__menu open&quot;]/div[@class=&quot;mobile__open&quot;]/nav[@class=&quot;mobile__kategorie_container&quot;]/div[2]/div[@class=&quot;mobile__kategoria__wrapper&quot;]</value>
      <webElementGuid>f7199d4e-d333-4e65-9868-1a8f040964de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header__mobile']/div/div[2]/div[2]/div/nav/div[2]/div</value>
      <webElementGuid>aa39e885-d6bd-4960-a098-16008b2decc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wszystkie kierunki'])[1]/following::div[3]</value>
      <webElementGuid>2da3bb47-a50e-4565-bf92-c314b7e5de62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubezpieczenia podróżne'])[1]/following::div[7]</value>
      <webElementGuid>e6ef3fee-4bbd-4ab7-a3a9-3675dd14b0d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Topniejące Rabaty'])[1]/preceding::div[3]</value>
      <webElementGuid>46aa0f3c-8cb4-415c-82c6-361379c45cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div[2]/div</value>
      <webElementGuid>50eed3c0-8b92-4ff8-bc96-6335f452cf32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Promocje' or . = 'Promocje')]</value>
      <webElementGuid>f1c8c950-816b-4e0e-a2a2-bcc37376cfeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
