<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SZUKAJ-hero</name>
   <tag></tag>
   <elementGuidId>fa95ebb2-e654-48af-b81f-b2d8b592f895</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/main/header/div/div/div[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.filtry__search.r-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a777ecfd-5980-488f-958d-af65fe26298e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/szukaj</value>
      <webElementGuid>6025279f-6fd5-4bfe-929c-58990fdfa3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Szukaj</value>
      <webElementGuid>ab0a632a-674f-4e8d-9246-ac8564b8505a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filtry__search r-button</value>
      <webElementGuid>19a9e2a7-7020-47b0-a889-29bfe24092bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      SZUKAJ
    </value>
      <webElementGuid>2800a951-c55a-4ab3-9afa-eb3e44f35c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/main[@class=&quot;strona-glowna&quot;]/header[@class=&quot;header-banner header-banner__webp&quot;]/div[@class=&quot;wrap wrap-header&quot;]/div[@class=&quot;filtry filtry&quot;]/div[@class=&quot;filtry__element filtry__element--search&quot;]/a[@class=&quot;filtry__search r-button&quot;]</value>
      <webElementGuid>1429f2f9-fb36-43ab-9cdf-52bd8bb8bdeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/header/div/div/div[6]/a</value>
      <webElementGuid>45747ad4-1235-432b-80c1-cfcd74f5d688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SZUKAJ')]</value>
      <webElementGuid>b4af5331-3488-41cb-b72d-43d74732efe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Samolot'])[1]/following::a[1]</value>
      <webElementGuid>492907bb-25ec-4a55-815d-1be13126addd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Typ Transportu'])[1]/following::a[1]</value>
      <webElementGuid>6fd2e0d5-3541-4f52-8505-315db0a52c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biuro podróży Rainbow'])[1]/preceding::a[1]</value>
      <webElementGuid>09cd99a8-3f28-49cc-ba53-9c39ea747999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Objazd + wypoczynek • Kuba: Varadero'])[1]/preceding::a[4]</value>
      <webElementGuid>d4deb498-9150-4384-90f4-69ae40595086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SZUKAJ']/parent::*</value>
      <webElementGuid>bb0f8163-4576-4803-91cc-1c55458e78e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/szukaj')]</value>
      <webElementGuid>239700b2-13f5-40b5-9e33-0828a9a88bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>b1f0bf5c-9f10-4f94-bc30-6156e7bb45c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/szukaj' and @title = 'Szukaj' and (text() = '
      SZUKAJ
    ' or . = '
      SZUKAJ
    ')]</value>
      <webElementGuid>e73668b2-bc13-4e1e-bb38-f7803b4dbe86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
