<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dowolna</name>
   <tag></tag>
   <elementGuidId>56b92e8a-0acc-4cfc-a5d8-b72d0f64cb72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/main/section/div/div[2]/div[2]/div/div[6]/section/div[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2fe52fd7-8313-447f-a2a6-4a5c9fbb2c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vue-radio radio-filter__radio marked</value>
      <webElementGuid>085513b4-0669-4c8a-998d-b619eb7d3b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  
    Dowolna
   </value>
      <webElementGuid>340e6e42-9732-45da-a438-64856d11c8d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/main[@class=&quot;szukaj&quot;]/section[@class=&quot;section no-padding&quot;]/div[@class=&quot;wrap szukaj-wrap&quot;]/div[@class=&quot;filtry-panel mobile-filtry-boczne mobile-filtry-boczne&quot;]/div[@class=&quot;filtry-panel__body&quot;]/div[@class=&quot;side-filters mobile-filtry-boczne__body&quot;]/div[@class=&quot;side-filters__filter&quot;]/section[@class=&quot;filter-section radio-filter&quot;]/div[@class=&quot;filter-section__content&quot;]/label[@class=&quot;vue-radio radio-filter__radio marked&quot;]</value>
      <webElementGuid>e9d4514a-0fd6-4227-ab02-c4fc98d6fcfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/section/div/div[2]/div[2]/div/div[6]/section/div[2]/label</value>
      <webElementGuid>c2771de5-c24f-4932-a198-f9c44b9f7ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ocena klientów'])[2]/following::label[1]</value>
      <webElementGuid>1586384c-f37f-42f5-879d-06cbaca5764c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard hotelu'])[2]/following::label[5]</value>
      <webElementGuid>4fedbd41-2d36-492c-9226-5e32a3a4f931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Od 5.0'])[2]/preceding::label[1]</value>
      <webElementGuid>78cc27fb-8283-4915-bd0f-ea2ef12a5f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[6]/section/div[2]/label</value>
      <webElementGuid>846bc91d-f91c-4cae-9763-49200191d6f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '  
    Dowolna
   ' or . = '  
    Dowolna
   ')]</value>
      <webElementGuid>8bc38994-2b5d-4249-825a-fb77d2868092</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
