<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Katowice</name>
   <tag></tag>
   <elementGuidId>02ce7bc9-b08a-4862-b597-12127fce9b9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/main/header/div/div/div[4]/div[2]/div[2]/div/div[2]/div/div/div[3]/label/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4e9733b5-094e-4bf1-aced-8a8f9de92996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kierunek__panstwo-text</value>
      <webElementGuid>e26e8f99-7c53-4263-96da-c7772c3a5903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katowice</value>
      <webElementGuid>6ba3553a-6504-41e9-a028-6d90ebc31e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/main[@class=&quot;szukaj&quot;]/header[@class=&quot;header-banner header-banner__webp r-header-mobile--display&quot;]/div[@class=&quot;wrap wrap-header&quot;]/div[@class=&quot;filtry filtry&quot;]/div[@class=&quot;filtry-input filtry__element filtry__element--skad filtry-input--no-clearable&quot;]/div[@class=&quot;filtry-panel filtry-panel--skad&quot;]/div[@class=&quot;filtry-panel__body&quot;]/div[@class=&quot;skad&quot;]/div[@class=&quot;skad__lista-kierunkow&quot;]/div[@class=&quot;lista-kierunkow__wrapper&quot;]/div[@class=&quot;lista-kierunkow__column&quot;]/div[@class=&quot;lista-kierunkow__row&quot;]/label[@class=&quot;vue-checkbox kierunek&quot;]/span[@class=&quot;vue-checkbox__text&quot;]/span[@class=&quot;kierunek__panstwo-text&quot;]</value>
      <webElementGuid>c1c6d2b5-e273-40ce-8b83-2104b5ef992d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/header/div/div/div[4]/div[2]/div[2]/div/div[2]/div/div/div[3]/label/span/span</value>
      <webElementGuid>aa58c20a-b334-4a94-9fc9-b592e3e25492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gdańsk'])[1]/following::span[2]</value>
      <webElementGuid>418369e1-c5d8-4c9f-acbc-11f2475f8670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bydgoszcz'])[1]/following::span[4]</value>
      <webElementGuid>59ee05b4-9253-4565-9a86-7cf8daf6ac6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kraków'])[1]/preceding::span[1]</value>
      <webElementGuid>d6aef1da-7f6f-4c7a-b9c7-117f48b56fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Łódź'])[1]/preceding::span[3]</value>
      <webElementGuid>24c4a214-78f6-4700-8f82-d25ee411b516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Katowice']/parent::*</value>
      <webElementGuid>e9d729be-58e6-47ca-a286-b52129db0546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/span/span</value>
      <webElementGuid>26fb5353-ccb3-4696-b8c7-0a7bbc29ab4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Katowice' or . = 'Katowice')]</value>
      <webElementGuid>cfe9109f-0b00-4c7a-8a8b-bd29316fd918</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
