<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Krakw</name>
   <tag></tag>
   <elementGuidId>30cee440-b2a1-4b61-bae3-bf35bec321a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/main/header/div/div/div[4]/div[2]/div[2]/div/div[2]/div/div/div[4]/label/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b83e8889-22dc-45c0-8d68-4f1fb46f6d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kierunek__panstwo-text</value>
      <webElementGuid>7da2d880-262c-4fb8-9fe9-1f472b46ccab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kraków</value>
      <webElementGuid>4b43b91a-dc2f-4b6e-b134-fe16fdbb26b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/main[@class=&quot;szukaj&quot;]/header[@class=&quot;header-banner header-banner__webp r-header-mobile--display&quot;]/div[@class=&quot;wrap wrap-header&quot;]/div[@class=&quot;filtry filtry&quot;]/div[@class=&quot;filtry-input filtry__element filtry__element--skad filtry-input--no-clearable&quot;]/div[@class=&quot;filtry-panel filtry-panel--skad&quot;]/div[@class=&quot;filtry-panel__body&quot;]/div[@class=&quot;skad&quot;]/div[@class=&quot;skad__lista-kierunkow&quot;]/div[@class=&quot;lista-kierunkow__wrapper&quot;]/div[@class=&quot;lista-kierunkow__column&quot;]/div[@class=&quot;lista-kierunkow__row&quot;]/label[@class=&quot;vue-checkbox kierunek&quot;]/span[@class=&quot;vue-checkbox__text&quot;]/span[@class=&quot;kierunek__panstwo-text&quot;]</value>
      <webElementGuid>51cdd239-4b69-441c-9642-d5ba2b92b858</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/header/div/div/div[4]/div[2]/div[2]/div/div[2]/div/div/div[4]/label/span/span</value>
      <webElementGuid>3b28e22f-c413-453b-80b1-04ddb08f4351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katowice'])[1]/following::span[2]</value>
      <webElementGuid>038abf21-536d-4dcc-acff-824039e8bd79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gdańsk'])[1]/following::span[4]</value>
      <webElementGuid>9b9fc3e0-70c0-43c6-9051-7a43fa38feb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Łódź'])[1]/preceding::span[1]</value>
      <webElementGuid>c6934a69-fd18-4608-807c-9b33607f131d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Poznań'])[1]/preceding::span[3]</value>
      <webElementGuid>017c2dd8-219b-4023-a0a7-f71253847ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kraków']/parent::*</value>
      <webElementGuid>0236d62c-d015-4cf7-8580-89b98450320d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/label/span/span</value>
      <webElementGuid>bd1ba842-24fd-4512-a39f-efb78735aad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Kraków' or . = 'Kraków')]</value>
      <webElementGuid>0195287d-51dd-439c-9346-a6056c981c08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
