<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Lodz</name>
   <tag></tag>
   <elementGuidId>0a129677-cd85-4369-9151-1f359b8c66a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/main/header/div/div/div[4]/div[2]/div[2]/div/div[2]/div/div/div[5]/label/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f366a020-db8f-41dc-bfc1-9704a4acdb9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kierunek__panstwo-text</value>
      <webElementGuid>87048b46-1739-47d7-876b-d0b6b2613697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Łódź</value>
      <webElementGuid>cb775ed4-333f-42af-b108-b521c48fa6d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/main[@class=&quot;szukaj&quot;]/header[@class=&quot;header-banner header-banner__webp r-header-mobile--display&quot;]/div[@class=&quot;wrap wrap-header&quot;]/div[@class=&quot;filtry filtry&quot;]/div[@class=&quot;filtry-input filtry__element filtry__element--skad filtry-input--no-clearable&quot;]/div[@class=&quot;filtry-panel filtry-panel--skad&quot;]/div[@class=&quot;filtry-panel__body&quot;]/div[@class=&quot;skad&quot;]/div[@class=&quot;skad__lista-kierunkow&quot;]/div[@class=&quot;lista-kierunkow__wrapper&quot;]/div[@class=&quot;lista-kierunkow__column&quot;]/div[@class=&quot;lista-kierunkow__row&quot;]/label[@class=&quot;vue-checkbox kierunek&quot;]/span[@class=&quot;vue-checkbox__text&quot;]/span[@class=&quot;kierunek__panstwo-text&quot;]</value>
      <webElementGuid>c5438284-8433-447b-9054-ac868cf232a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/header/div/div/div[4]/div[2]/div[2]/div/div[2]/div/div/div[5]/label/span/span</value>
      <webElementGuid>d93d51a8-74f5-4251-985b-2047c2a144c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kraków'])[1]/following::span[2]</value>
      <webElementGuid>5cd50ac6-54c5-48c2-98ee-b9187a3630de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katowice'])[1]/following::span[4]</value>
      <webElementGuid>0d76008a-4069-4a14-82ae-ac807a00e6df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Poznań'])[1]/preceding::span[1]</value>
      <webElementGuid>d7fb7080-521b-41b2-b8be-e1283dc491f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rzeszów'])[1]/preceding::span[3]</value>
      <webElementGuid>799ec397-52a6-4868-b0ab-152240c8190a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Łódź']/parent::*</value>
      <webElementGuid>e7ba60f6-7503-40ae-a9e4-b213ce5c5787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label/span/span</value>
      <webElementGuid>a504add2-6623-49bf-b3bd-7458bf15c030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Łódź' or . = 'Łódź')]</value>
      <webElementGuid>b6820269-fa1d-493c-9a0a-c5d6349b5d6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
