<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Wroclaw</name>
   <tag></tag>
   <elementGuidId>f58af25f-a80b-4927-84fd-e8593050e591</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/main/header/div/div/div[4]/div[2]/div[2]/div/div[2]/div/div/div[11]/label/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a79fbf56-30a4-498d-b99f-b952baae37c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kierunek__panstwo-text</value>
      <webElementGuid>35c30910-2cee-4c2e-94d5-9a5c939b33af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wrocław</value>
      <webElementGuid>6c6daf3e-db88-426c-92eb-f68c9ba604e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/main[@class=&quot;szukaj&quot;]/header[@class=&quot;header-banner header-banner__webp r-header-mobile--display&quot;]/div[@class=&quot;wrap wrap-header&quot;]/div[@class=&quot;filtry filtry&quot;]/div[@class=&quot;filtry-input filtry__element filtry__element--skad filtry-input--no-clearable&quot;]/div[@class=&quot;filtry-panel filtry-panel--skad&quot;]/div[@class=&quot;filtry-panel__body&quot;]/div[@class=&quot;skad&quot;]/div[@class=&quot;skad__lista-kierunkow&quot;]/div[@class=&quot;lista-kierunkow__wrapper&quot;]/div[@class=&quot;lista-kierunkow__column&quot;]/div[@class=&quot;lista-kierunkow__row&quot;]/label[@class=&quot;vue-checkbox kierunek&quot;]/span[@class=&quot;vue-checkbox__text&quot;]/span[@class=&quot;kierunek__panstwo-text&quot;]</value>
      <webElementGuid>a779ca47-792f-4418-951f-5f1dcadc34e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/header/div/div/div[4]/div[2]/div[2]/div/div[2]/div/div/div[11]/label/span/span</value>
      <webElementGuid>87d8e182-826f-4eae-b2fd-31c4e9d40bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warszawa Modlin'])[1]/following::span[2]</value>
      <webElementGuid>623fc6ee-fe90-4ce8-a40a-1dfe6ff1b1a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warszawa Chopin'])[1]/following::span[4]</value>
      <webElementGuid>51e4ac15-5f19-4e34-aa86-66cd3717b396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='wyczyść'])[1]/preceding::span[1]</value>
      <webElementGuid>60ad6cf1-8549-4f31-86ee-2272c07995fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='wybierz'])[1]/preceding::span[1]</value>
      <webElementGuid>73fef73e-af7e-4851-b3f1-fff4c6abb1f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Wrocław']/parent::*</value>
      <webElementGuid>2e8bf404-0ed4-4cf1-b3a8-84e7510ebab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/label/span/span</value>
      <webElementGuid>f1178301-200d-4c30-9234-e5dac349dfd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Wrocław' or . = 'Wrocław')]</value>
      <webElementGuid>1b437470-cc0b-4b5e-a2fc-cf225a8dbee0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
