<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Poznan</name>
   <tag></tag>
   <elementGuidId>36657984-433e-40f2-a9a5-c9825bf754e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/main/header/div/div/div[4]/div[2]/div[2]/div/div[2]/div/div/div[6]/label/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9a461c4f-4826-427c-a8ef-1bcaacf3eeb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kierunek__panstwo-text</value>
      <webElementGuid>2d012c78-5db6-4f50-8af5-859c85cc0edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Poznań</value>
      <webElementGuid>d6a013fe-85bc-49ff-801c-95035fcbe8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/main[@class=&quot;szukaj&quot;]/header[@class=&quot;header-banner header-banner__webp r-header-mobile--display&quot;]/div[@class=&quot;wrap wrap-header&quot;]/div[@class=&quot;filtry filtry&quot;]/div[@class=&quot;filtry-input filtry__element filtry__element--skad filtry-input--no-clearable&quot;]/div[@class=&quot;filtry-panel filtry-panel--skad&quot;]/div[@class=&quot;filtry-panel__body&quot;]/div[@class=&quot;skad&quot;]/div[@class=&quot;skad__lista-kierunkow&quot;]/div[@class=&quot;lista-kierunkow__wrapper&quot;]/div[@class=&quot;lista-kierunkow__column&quot;]/div[@class=&quot;lista-kierunkow__row&quot;]/label[@class=&quot;vue-checkbox kierunek&quot;]/span[@class=&quot;vue-checkbox__text&quot;]/span[@class=&quot;kierunek__panstwo-text&quot;]</value>
      <webElementGuid>c78c713f-2070-4ae0-acc4-b929fffca09b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/header/div/div/div[4]/div[2]/div[2]/div/div[2]/div/div/div[6]/label/span/span</value>
      <webElementGuid>885d42c2-862b-4caa-b2b1-d8715f2751cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Łódź'])[1]/following::span[2]</value>
      <webElementGuid>eb138baa-ff01-427d-9a8f-3f009d5b444a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kraków'])[1]/following::span[4]</value>
      <webElementGuid>42d8c0f1-af23-4683-a206-5d01c521a7fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rzeszów'])[1]/preceding::span[1]</value>
      <webElementGuid>b1643761-5d94-4b8c-aeaa-67a93b1c20c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Szczecin'])[1]/preceding::span[3]</value>
      <webElementGuid>0a75dc39-3cc8-4239-aa28-177d1f862e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Poznań']/parent::*</value>
      <webElementGuid>58cb5b54-da97-42ad-9d36-e117c2a2d1f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/label/span/span</value>
      <webElementGuid>181f6f36-c541-42ba-a5b6-9355bd470e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Poznań' or . = 'Poznań')]</value>
      <webElementGuid>d6641e3d-17a4-419a-bfa3-ccda5c4a7144</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
