<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>blog-articles__wrap</name>
   <tag></tag>
   <elementGuidId>6b9c2e45-fe9e-4374-820a-4d3e4e2569ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/main/section[6]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.blog.strona-glowna__blog</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b04a51ec-765d-44de-b489-560ae0bfcdc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blog strona-glowna__blog</value>
      <webElementGuid>7b808beb-2285-4200-9579-7d38141cc525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  30.06.2022 Pogoda, klimat i temperatury w Portugalii. Kiedy jechać do Lizbony i Algarve? Słynąca z fantastycznej kuchni, piłki nożnej, muzyki fado oraz przepięknej przyrody i architektury Portugalia to wymarzone miejsce na wakacje. Znajdziemy tu zarówno wspaniałe piaszczyste plaże, jak i widowiskowe klify oraz urokliwe zatoczki. Na miłośników zwiedzania czeka stołeczna Lizbona, położone u ...   28.06.2022 Pogoda, klimat i średnie temperatury w Hiszpanii Hiszpania to jedna z najciekawszych destynacji wakacyjnych w Europie. Znajdziemy tu ciepłe morze, wspaniałe plaże z mnóstwem przytulnych knajpek, gdzie można rozsmakować się w miejscowej kuchni oraz bogatą kulturę, która m.in. zrodziła muzykę flamenco. Warto też wiedzieć, że Hiszpania to także raj dla osób zainteresowanych ...   27.06.2022 Egzotyka z Gdańska bezpośrednio Dreamlinerem! Nowe połączenia już od listopada Dominikana, Meksyk, Kuba, Tajlandia – do tych egzotycznych miejsc Rainbow zabierze Klientów już tej jesieni. Po raz pierwszy w historii bezpośrednio Dreamlinerem z lotniska w Gdańsku. Podróż rozpocznie się z oddanego do użytku w ostatni czwartek nowego pirsu zachodniego Terminala T2. Uroczystość otwarcia połączona zos...</value>
      <webElementGuid>9d31aecb-74a8-4f19-9f51-4517226312cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/main[@class=&quot;strona-glowna&quot;]/section[@class=&quot;section&quot;]/div[@class=&quot;wrap&quot;]/div[@class=&quot;blog strona-glowna__blog&quot;]</value>
      <webElementGuid>08f795fe-4660-4c58-948a-3cc23ebe3cff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/section[6]/div/div[2]</value>
      <webElementGuid>5219cfa4-3d2d-4770-bda1-a9a9ab90dd33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='blog'])[1]/following::div[1]</value>
      <webElementGuid>6853216c-fc10-41d3-af95-9585d6af3c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='od 6 144 zł'])[1]/following::div[3]</value>
      <webElementGuid>376e5e2a-0ec5-4687-bca4-414995b88759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[5]/div/div[2]</value>
      <webElementGuid>a2ef611d-e92f-4b4b-b79f-d5303a69371c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '  30.06.2022 Pogoda, klimat i temperatury w Portugalii. Kiedy jechać do Lizbony i Algarve? Słynąca z fantastycznej kuchni, piłki nożnej, muzyki fado oraz przepięknej przyrody i architektury Portugalia to wymarzone miejsce na wakacje. Znajdziemy tu zarówno wspaniałe piaszczyste plaże, jak i widowiskowe klify oraz urokliwe zatoczki. Na miłośników zwiedzania czeka stołeczna Lizbona, położone u ...   28.06.2022 Pogoda, klimat i średnie temperatury w Hiszpanii Hiszpania to jedna z najciekawszych destynacji wakacyjnych w Europie. Znajdziemy tu ciepłe morze, wspaniałe plaże z mnóstwem przytulnych knajpek, gdzie można rozsmakować się w miejscowej kuchni oraz bogatą kulturę, która m.in. zrodziła muzykę flamenco. Warto też wiedzieć, że Hiszpania to także raj dla osób zainteresowanych ...   27.06.2022 Egzotyka z Gdańska bezpośrednio Dreamlinerem! Nowe połączenia już od listopada Dominikana, Meksyk, Kuba, Tajlandia – do tych egzotycznych miejsc Rainbow zabierze Klientów już tej jesieni. Po raz pierwszy w historii bezpośrednio Dreamlinerem z lotniska w Gdańsku. Podróż rozpocznie się z oddanego do użytku w ostatni czwartek nowego pirsu zachodniego Terminala T2. Uroczystość otwarcia połączona zos...' or . = '  30.06.2022 Pogoda, klimat i temperatury w Portugalii. Kiedy jechać do Lizbony i Algarve? Słynąca z fantastycznej kuchni, piłki nożnej, muzyki fado oraz przepięknej przyrody i architektury Portugalia to wymarzone miejsce na wakacje. Znajdziemy tu zarówno wspaniałe piaszczyste plaże, jak i widowiskowe klify oraz urokliwe zatoczki. Na miłośników zwiedzania czeka stołeczna Lizbona, położone u ...   28.06.2022 Pogoda, klimat i średnie temperatury w Hiszpanii Hiszpania to jedna z najciekawszych destynacji wakacyjnych w Europie. Znajdziemy tu ciepłe morze, wspaniałe plaże z mnóstwem przytulnych knajpek, gdzie można rozsmakować się w miejscowej kuchni oraz bogatą kulturę, która m.in. zrodziła muzykę flamenco. Warto też wiedzieć, że Hiszpania to także raj dla osób zainteresowanych ...   27.06.2022 Egzotyka z Gdańska bezpośrednio Dreamlinerem! Nowe połączenia już od listopada Dominikana, Meksyk, Kuba, Tajlandia – do tych egzotycznych miejsc Rainbow zabierze Klientów już tej jesieni. Po raz pierwszy w historii bezpośrednio Dreamlinerem z lotniska w Gdańsku. Podróż rozpocznie się z oddanego do użytku w ostatni czwartek nowego pirsu zachodniego Terminala T2. Uroczystość otwarcia połączona zos...')]</value>
      <webElementGuid>74faa251-dac3-4b31-a54e-23e7d337b37a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
