<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>blog-articles__first-element</name>
   <tag></tag>
   <elementGuidId>a641abdd-b73f-4c84-b7ed-7ae510b7b6c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[2]/main/section[5]/div/div[2]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.lazy-image__img.artykul__image.lazyLoad.isLoaded</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'blog__left']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>963e30b5-80f7-4ecf-ba41-500e0b64f68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blog__left</value>
      <webElementGuid>f76944e0-dd1a-4bc1-9530-becb0e53f13b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//images.r.pl/zdjecia/lokalizacje/71/portugalia_71_104896_156274_1000x1000.jpg</value>
      <webElementGuid>4aab142a-7c47-462b-a4ad-4a8980a71b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__layout&quot;]/div/div[2]/main/section[6]/div/div[2]/div[1]</value>
      <webElementGuid>cf331571-74e6-4cda-8c42-501ef6a75632</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/section[5]/div/div[2]/div/a/div/img</value>
      <webElementGuid>c739bd2a-7312-4afa-8454-3eb0cbe3b506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/a/div/img</value>
      <webElementGuid>813e9c6a-ada8-4d0b-9da1-ee95c7466361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//images.r.pl/zdjecia/lokalizacje/71/portugalia_71_104896_156274_1000x1000.jpg']</value>
      <webElementGuid>95ad18c5-63f2-4906-b3ad-69b24ddfa43c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
