<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>blog-articles__first-element</name>
   <tag></tag>
   <elementGuidId>a641abdd-b73f-4c84-b7ed-7ae510b7b6c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[2]/main/section[5]/div/div[2]/div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'blog__left']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.lazy-image__img.artykul__image.lazyLoad.isLoaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>178b2ca8-b903-46fa-97e2-de65768c69f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blog__left</value>
      <webElementGuid>f4abb49a-3d8b-4e71-ae49-a9ac9ce79f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//images.r.pl/zdjecia/lokalizacje/71/portugalia_71_104896_156274_1000x1000.jpg</value>
      <webElementGuid>3bea2483-f382-498d-8c98-44bff104bdb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__layout&quot;]/div/div[2]/main/section[5]/div/div[2]/div[1]</value>
      <webElementGuid>5722f876-9fb3-47e1-94ed-d82066103ff4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/section[5]/div/div[2]/div/a/div/img</value>
      <webElementGuid>343e1123-7a78-4bdd-a225-01c81d1bda01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/a/div/img</value>
      <webElementGuid>30360596-9202-4ae3-b09f-2c603d40fb28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//images.r.pl/zdjecia/lokalizacje/71/portugalia_71_104896_156274_1000x1000.jpg']</value>
      <webElementGuid>1feed600-ad2f-438d-957d-e2ea792c40ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
