<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Header-blog</name>
   <tag></tag>
   <elementGuidId>0e92ed7d-ea44-4e42-843a-b756c37adb56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/main/section[5]/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.section-header.blog-header-text.h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>0edaf2a6-203c-48d3-b81e-8b31de67ea51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-header blog-header-text h3</value>
      <webElementGuid>8044caff-6fff-4cf0-85d5-c78a7a25ef4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        blog
      </value>
      <webElementGuid>1fba2e41-4b82-4565-bef6-b3feaddd76a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/main[@class=&quot;strona-glowna&quot;]/section[@class=&quot;section&quot;]/div[@class=&quot;wrap&quot;]/h2[@class=&quot;section-header blog-header-text h3&quot;]</value>
      <webElementGuid>46435df2-1280-4fbf-82fb-db6f9722ae5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/section[5]/div/h2</value>
      <webElementGuid>3b76e495-a2a8-44be-9ecf-a48d45aad4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='od 6 144 zł'])[1]/following::h2[1]</value>
      <webElementGuid>6d755b7c-2fcb-4947-9110-cd5c74bffb94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meksyk'])[1]/following::h2[1]</value>
      <webElementGuid>3e80833b-988e-4554-8ec1-af5fdf8676db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pogoda, klimat i temperatury w Portugalii. Kiedy jechać do Lizbony i Algarve?'])[1]/preceding::h2[1]</value>
      <webElementGuid>bd24f870-19eb-4d4e-8752-b8ea664cf43e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pogoda, klimat i średnie temperatury w Hiszpanii'])[1]/preceding::h2[1]</value>
      <webElementGuid>d9622dfc-4639-42fa-9459-dd0754127021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='blog']/parent::*</value>
      <webElementGuid>1404268e-50fc-4e39-bdde-47b3ee42c9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[5]/div/h2</value>
      <webElementGuid>5e96e2f5-43bd-4fc1-974a-807b1c0e204b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = '
        blog
      ' or . = '
        blog
      ')]</value>
      <webElementGuid>d09126ea-7f66-4657-83ba-a0743d115b24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
