<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Header-blog</name>
   <tag></tag>
   <elementGuidId>0e92ed7d-ea44-4e42-843a-b756c37adb56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/main/section[6]/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.section-header.blog-header-text.h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>5f976a15-611b-46bc-bca3-9aae89df316b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-header blog-header-text h3</value>
      <webElementGuid>c2fb9067-db7b-4d30-b818-0667cf6951af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        blog
      </value>
      <webElementGuid>ea7c4d2f-55cd-4ba9-a286-efe7b1686e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/main[@class=&quot;strona-glowna&quot;]/section[@class=&quot;section&quot;]/div[@class=&quot;wrap&quot;]/h2[@class=&quot;section-header blog-header-text h3&quot;]</value>
      <webElementGuid>2a004797-df71-4e3a-b026-04e427b9b7eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/section[6]/div/h2</value>
      <webElementGuid>627793ac-9c3d-4776-a774-221d8dea0d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='od 6 144 zł'])[1]/following::h2[1]</value>
      <webElementGuid>77911100-e7a1-425d-915c-7cb95d239e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meksyk'])[1]/following::h2[1]</value>
      <webElementGuid>f9d0e7f0-3e9e-47c6-8542-aedf841a825a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pogoda, klimat i temperatury w Portugalii. Kiedy jechać do Lizbony i Algarve?'])[1]/preceding::h2[1]</value>
      <webElementGuid>9c3b1c32-9f3e-44cc-b9e4-1eb2493c44c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pogoda, klimat i średnie temperatury w Hiszpanii'])[1]/preceding::h2[1]</value>
      <webElementGuid>c1986244-efc3-447c-bbb3-84dbaa55c924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='blog']/parent::*</value>
      <webElementGuid>67a32815-6b23-4bd3-bc75-1ce567635449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[6]/div/h2</value>
      <webElementGuid>d6bac17a-3dee-410a-8efc-4df2b31da90a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = '
        blog
      ' or . = '
        blog
      ')]</value>
      <webElementGuid>e5771ff9-692c-44ff-b375-1f5128b1f417</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
