<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slider__Turcja-btn</name>
   <tag></tag>
   <elementGuidId>db46552e-4cc9-458e-93c7-bc45884a512f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='carusel']/div/ul/li[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>43d23c00-e8a6-41e5-b6bd-338a89511d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>7434aaa9-4730-424a-8376-52b23c25f00a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabs__tab</value>
      <webElementGuid>2bcffd02-9806-4287-90e5-8aaf706da4e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Turcja
      </value>
      <webElementGuid>12404ab7-fb8a-4ae3-83f5-a3224bef4329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carusel&quot;)/div[@class=&quot;tabs&quot;]/ul[@class=&quot;tabs__nav full-width&quot;]/li[@class=&quot;tabs__tab&quot;]</value>
      <webElementGuid>47f8065f-b17b-43e5-8a7e-6fc7c6b21d81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='carusel']/div/ul/li[3]</value>
      <webElementGuid>bc79e9af-3e79-49df-993e-5946639a6f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Minute'])[2]/following::li[1]</value>
      <webElementGuid>81997175-cd19-48b8-8f97-c02ab23759aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Topniejące Rabaty'])[1]/following::li[2]</value>
      <webElementGuid>70a95a03-94fa-4cb2-acdd-a747bd1ceba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Egzotyka 2022/2023'])[1]/preceding::li[1]</value>
      <webElementGuid>fdc25454-b30f-45ca-a917-963365af1a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Turcja']/parent::*</value>
      <webElementGuid>4b92f0ad-5de4-4723-8512-bb99af055110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]</value>
      <webElementGuid>4d87cde8-cd4d-4dda-aa55-a9714dcafe3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '
        Turcja
      ' or . = '
        Turcja
      ')]</value>
      <webElementGuid>f0e0b3a4-2e9e-45eb-ae28-ed09884f69fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
