<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slider__Turcja</name>
   <tag></tag>
   <elementGuidId>ccd596c9-5a1a-49b8-a800-b126e570eae9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[2]/main/section[1]/div/div/div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;__layout&quot;]/div/div[2]/main/section[1]/div/div/div[2][count(. | //div[@class = 'promocje promocje--csr']) = count(//div[@class = 'promocje promocje--csr'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__layout&quot;]/div/div[2]/main/section[1]/div/div/div[2]</value>
      <webElementGuid>a4d4e259-9db2-4914-9ee0-a2bef2dd54b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0e58aa8b-c23e-443a-8248-cd261d955782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>promocje promocje--csr</value>
      <webElementGuid>58c8a21a-5d81-470d-9409-e1c53fe09b45</webElementGuid>
   </webElementProperties>
</WebElementEntity>
