<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>newsletter-box</name>
   <tag></tag>
   <elementGuidId>846af513-bfb0-4183-9e4d-58e487f99fe5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[4]/footer/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.newsletter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a20ffe3a-e249-47c5-a0fc-d89c4d35f9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>newsletter</value>
      <webElementGuid>8683d219-949d-4521-85c9-15d13636e651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jeśli chcesz jako pierwszy otrzymać najlepsze oferty wprost na Twoją skrzynkę,ZAPISZ SIĘ NA NEWSLETTER: ZAPISZ SIĘ Administratorem Twoich danych jest RAINBOW TOURS SA  KLIKNIJ i dowiedz się więcej o ochronie Twoich danych. </value>
      <webElementGuid>b44ab01c-37c9-4436-a3c7-ee6ec985ef95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;footer__background&quot;]/footer[@class=&quot;footer&quot;]/div[@class=&quot;footer__box-top&quot;]/div[@class=&quot;newsletter&quot;]</value>
      <webElementGuid>3a90a1bf-f02c-4cd1-8020-62685d2b7d6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[4]/footer/div/div[2]</value>
      <webElementGuid>534a3ee0-d45c-4cf4-9ff5-a0480c9430c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biura Rainbow'])[1]/following::div[1]</value>
      <webElementGuid>3531b022-ef89-4cf8-a3f1-a4dc14985024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='callcenter@r.pl'])[1]/following::div[3]</value>
      <webElementGuid>bf73f502-52b0-46e3-9d07-dcdd81796e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div[2]</value>
      <webElementGuid>4571698e-65ba-40ed-b2ff-e0ac941af4b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Jeśli chcesz jako pierwszy otrzymać najlepsze oferty wprost na Twoją skrzynkę,ZAPISZ SIĘ NA NEWSLETTER: ZAPISZ SIĘ Administratorem Twoich danych jest RAINBOW TOURS SA  KLIKNIJ i dowiedz się więcej o ochronie Twoich danych. ' or . = 'Jeśli chcesz jako pierwszy otrzymać najlepsze oferty wprost na Twoją skrzynkę,ZAPISZ SIĘ NA NEWSLETTER: ZAPISZ SIĘ Administratorem Twoich danych jest RAINBOW TOURS SA  KLIKNIJ i dowiedz się więcej o ochronie Twoich danych. ')]</value>
      <webElementGuid>358a102e-8567-4113-a6d8-7e7b1e3bcb79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
