<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>destination-box__place</name>
   <tag></tag>
   <elementGuidId>4e5d6750-4456-4e2a-a512-1d446fc18692</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.seo-long__text--country</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/main/section[2]/div/div/div/div/div/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3eccb1d6-658b-498c-81a7-e6cd9e9f2f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>seo-long__text--country</value>
      <webElementGuid>e1108e99-6855-46a5-aced-b13005f0a829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Grecja
        </value>
      <webElementGuid>082afe46-1c21-46a2-9cd7-ba58e450302b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/main[@class=&quot;szukaj&quot;]/section[@class=&quot;section blue-Gradient&quot;]/div[@class=&quot;wrap&quot;]/div[1]/div[@class=&quot;seo-long__container background&quot;]/div[@class=&quot;seo-long__container--row&quot;]/div[@class=&quot;seo-long__container--col w44&quot;]/div[@class=&quot;seo-long__container--country&quot;]/div[@class=&quot;seo-long__text--country&quot;]</value>
      <webElementGuid>49b757da-d1fb-45ab-9c15-75b0fe5e9665</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/section[2]/div/div/div/div/div/div[2]/div[2]</value>
      <webElementGuid>a07a4a65-256a-4398-b58c-071f1c38d7b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mapa'])[1]/following::div[9]</value>
      <webElementGuid>38c133a7-b9aa-400e-b405-36c8f45d9cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lista'])[1]/following::div[10]</value>
      <webElementGuid>8e6a9a97-a314-412e-a9b9-8de449286679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ateny'])[1]/preceding::div[1]</value>
      <webElementGuid>4bdf50af-26ae-48c2-909f-6508794d17a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/div/div/div[2]/div[2]</value>
      <webElementGuid>47f963bd-1ea1-46bb-b3cd-c78cad0e26e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
          Grecja
        ' or . = '
          Grecja
        ')]</value>
      <webElementGuid>fc787440-57dc-4c1f-b2e4-fb73b2f44067</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
