<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slider__Egzotyka-firstEle</name>
   <tag></tag>
   <elementGuidId>8c1ed3a0-470a-46d9-9487-abfb3f51840e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[2]/main/section[1]/div/div/div[1]/div/div[1]/article/div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;__layout&quot;]/div/div[2]/main/section[1]/div/div/div[1]/div/div[1]/article/div[1][count(. | //div[@class = 'promocje__item first']) = count(//div[@class = 'promocje__item first'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__layout&quot;]/div/div[2]/main/section[1]/div/div/div[1]/div/div[1]/article/div[1]</value>
      <webElementGuid>975af80f-8177-4026-bc22-b7eb0a44021d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1cff0f93-6498-49cc-90ed-f0b8941c1a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>promocje__item first</value>
      <webElementGuid>03814a54-6589-4a9b-b55a-945b082d7b3c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
