<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-dot-3</name>
   <tag></tag>
   <elementGuidId>640ba164-51af-4cb9-baf6-f1cacce3c651</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/main/section[6]/div/div/div[2]/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d4c48c11-9387-422f-8285-d891a8394816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>seo-section__dots</value>
      <webElementGuid>777c11dc-88d7-4017-b468-e75ef04f9f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/main[@class=&quot;strona-glowna&quot;]/section[@class=&quot;section section gray&quot;]/div[@class=&quot;wrap&quot;]/div[1]/div[@class=&quot;seo-section__dots-wrapper&quot;]/div[@class=&quot;seo-section__dots&quot;]</value>
      <webElementGuid>b1121332-6f17-419c-8ac2-cd7f0f7dced0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/section[6]/div/div/div[2]/div[3]</value>
      <webElementGuid>039a8c4e-5967-45cc-bf5c-664b05ea07a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[6]/div/div/div[2]/div[3]</value>
      <webElementGuid>3fe2cd2a-3c99-4e83-9f43-8ed637a75612</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
