<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Akordeon-pierwszy-ele-mobile</name>
   <tag></tag>
   <elementGuidId>4c07acc0-c65c-4d26-ab84-564a7e5f9fdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;__layout&quot;]/div/div[2]/main/section[2]/div/div/div/div[1]/div[2]/div[count(. | //div[@class = 'accordion-seo__container']) = count(//div[@class = 'accordion-seo__container'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.accordion__text--head</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[2]/main/section[2]/div/div/div/div[1]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>35c8841b-c74b-4fcf-84bf-8e2e3e02ba86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-seo__container</value>
      <webElementGuid>e0f9ccdd-04ec-46c3-90fc-ba09d6606149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Co warto wiedzieć przed podróżą do Albanii – praktyczny przewodnik </value>
      <webElementGuid>eec5255a-0de8-4493-841d-33c7b9d2b5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__layout&quot;]/div/div[2]/main/section[2]/div/div/div/div[1]/div[2]/div</value>
      <webElementGuid>19df2209-bb57-4b6d-916b-b89ceb088ed7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
