<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Akordeon-pierwszy-ele-mobile</name>
   <tag></tag>
   <elementGuidId>4c07acc0-c65c-4d26-ab84-564a7e5f9fdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[2]/main/section[2]/div/div/div/div[1]/div[2]/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;__layout&quot;]/div/div[2]/main/section[2]/div/div/div/div[1]/div[2]/div[count(. | //div[@class = 'accordion-seo__container']) = count(//div[@class = 'accordion-seo__container'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.accordion__text--head</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2fed9a32-d023-4a49-90fe-379966add082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-seo__container</value>
      <webElementGuid>575c978f-a2be-4cb5-bb38-a2ae0983683e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Co warto wiedzieć przed podróżą do Albanii – praktyczny przewodnik </value>
      <webElementGuid>d1911567-53e6-461b-9520-4b0b48041ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__layout&quot;]/div/div[2]/main/section[2]/div/div/div/div[1]/div[2]/div</value>
      <webElementGuid>190fefa5-ea44-412e-8560-67d129c79925</webElementGuid>
   </webElementProperties>
</WebElementEntity>
