<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Wycieczki fakultatywne</name>
   <tag></tag>
   <elementGuidId>c30b23dc-b01a-408a-9ff1-71c0deb0fc70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainHeader']/div/div/header/nav/div/div/div[3]/div/div[4]/div/a/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6e26752a-3d72-42c6-b1af-4e6c203b6d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktop__kafelek-text</value>
      <webElementGuid>5d32a8d5-c17e-4384-8312-ba6ef997dbe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wycieczki fakultatywne</value>
      <webElementGuid>07829027-56f0-4fae-a6ba-e8ecd5864936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainHeader&quot;)/div[@class=&quot;header__desktop&quot;]/div[@class=&quot;desktop__header-position&quot;]/header[@class=&quot;desktop__container-position&quot;]/nav[@class=&quot;desktop__container-kategorie&quot;]/div[1]/div[@class=&quot;desktop__podkategorie-wrapper&quot;]/div[3]/div[@class=&quot;desktop__podkategorie-rzad&quot;]/div[4]/div[1]/a[@class=&quot;footer-men__siteMap__link desktop&quot;]/div[@class=&quot;desktop__kafelek&quot;]/span[@class=&quot;desktop__kafelek-text&quot;]</value>
      <webElementGuid>a4b30da8-6ba9-4883-99e4-fde2f7b7a4c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainHeader']/div/div/header/nav/div/div/div[3]/div/div[4]/div/a/div/span</value>
      <webElementGuid>b459882c-10c7-4fb4-ac16-350eafb640da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotele White Olive'])[1]/following::span[1]</value>
      <webElementGuid>ce19ed15-5426-4f34-a664-cbf9467969ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City Break'])[1]/following::span[2]</value>
      <webElementGuid>10688885-0a90-4045-891c-81bef88db802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Przelot Dreamlinerem'])[1]/preceding::span[1]</value>
      <webElementGuid>b5d22b30-5ad2-46d6-a10d-c1030fd036d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parking przy lotnisku'])[1]/preceding::span[2]</value>
      <webElementGuid>aa56242f-8da6-4fcf-ad15-7adfede78991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Wycieczki fakultatywne']/parent::*</value>
      <webElementGuid>d2f14d9f-fe29-477e-9c46-f9e4f44b2a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[4]/div/a/div/span</value>
      <webElementGuid>b8595fbb-d64f-4b55-9d70-c5e2945de6f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Wycieczki fakultatywne' or . = 'Wycieczki fakultatywne')]</value>
      <webElementGuid>d58f6f37-d63c-4120-b966-1101b66c92e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
