<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hotele Elite</name>
   <tag></tag>
   <elementGuidId>5602acbe-0ace-4b6c-832f-8bc7911f33b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainHeader']/div/div/header/nav/div/div/div[2]/div/div[2]/div/a/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6d231632-61d0-475c-b256-a74b249524eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktop__kafelek-text</value>
      <webElementGuid>139a1793-7fb2-465b-821c-f09cdf903b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hotele Elite</value>
      <webElementGuid>17ee815d-21e4-4a3d-a725-e6a66d2a3fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainHeader&quot;)/div[@class=&quot;header__desktop&quot;]/div[@class=&quot;desktop__header-position&quot;]/header[@class=&quot;desktop__container-position&quot;]/nav[@class=&quot;desktop__container-kategorie&quot;]/div[1]/div[@class=&quot;desktop__podkategorie-wrapper&quot;]/div[2]/div[@class=&quot;desktop__podkategorie-rzad&quot;]/div[2]/div[1]/a[@class=&quot;footer-men__siteMap__link desktop&quot;]/div[@class=&quot;desktop__kafelek&quot;]/span[@class=&quot;desktop__kafelek-text&quot;]</value>
      <webElementGuid>8d707926-7bfd-4217-92e3-594ae45ba939</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainHeader']/div/div/header/nav/div/div/div[2]/div/div[2]/div/a/div/span</value>
      <webElementGuid>92ee7958-cce8-4fd6-b2db-ffeab6508dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All inclusive'])[1]/following::span[1]</value>
      <webElementGuid>f9d3b705-f54a-4e33-934b-8d45b31f07a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dojazd własny'])[1]/following::span[2]</value>
      <webElementGuid>b94670b4-7ace-4bb4-a05b-273f54fdd055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wakacje z dziećmi'])[1]/preceding::span[1]</value>
      <webElementGuid>e8967141-c98c-433f-8881-4d444db50189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autokarem z Polski'])[1]/preceding::span[2]</value>
      <webElementGuid>1e6c81a0-830e-483e-b016-878322386e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hotele Elite']/parent::*</value>
      <webElementGuid>99e5b3f3-835d-4a8c-b2ac-c4b100a95b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/a/div/span</value>
      <webElementGuid>dfefe8c0-0f9f-414b-9562-c7a2c3339ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Hotele Elite' or . = 'Hotele Elite')]</value>
      <webElementGuid>0a07c58f-cdb8-4f01-89ed-c4453a9c4f9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
