<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Blog</name>
   <tag></tag>
   <elementGuidId>0db022c8-b0fd-4d1d-a091-8a494ff31dbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainHeader']/div/div/header/nav/div[6]/a/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c747c200-5631-4738-b2a3-aae07e383e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktop__kategoria-text</value>
      <webElementGuid>1644b186-ed6f-41b6-990b-14aa9431a95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Blog</value>
      <webElementGuid>a595bc71-4b56-4e0e-8711-5d2e18b48681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainHeader&quot;)/div[@class=&quot;header__desktop&quot;]/div[@class=&quot;desktop__header-position&quot;]/header[@class=&quot;desktop__container-position&quot;]/nav[@class=&quot;desktop__container-kategorie&quot;]/div[6]/a[@class=&quot;desktop__kategorie_siteMap__link&quot;]/div[@class=&quot;desktop__kategoria-wrapper&quot;]/span[@class=&quot;desktop__kategoria-text&quot;]</value>
      <webElementGuid>e57a2523-48cb-461d-8237-d98fddead8e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainHeader']/div/div/header/nav/div[6]/a/div/span</value>
      <webElementGuid>c9693119-5a61-40e4-8f9b-dd302898459a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wycieczki fakultatywne'])[2]/following::span[1]</value>
      <webElementGuid>a13233f9-7820-4a91-8308-04d7604efc95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Czartery'])[1]/following::span[2]</value>
      <webElementGuid>4a925993-0d83-400d-941d-d173675ea90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokąd chcesz jechać?'])[1]/preceding::span[1]</value>
      <webElementGuid>6314341f-2756-476c-97a0-c419e641c105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gdziekolwiek'])[1]/preceding::span[1]</value>
      <webElementGuid>024fa5e4-02e8-4dd3-9df1-fe49cc000a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Blog']/parent::*</value>
      <webElementGuid>2fc09261-9f81-45ea-8e5d-df5820fd6594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a/div/span</value>
      <webElementGuid>ab540dd5-f85d-4640-bd39-5572bb789d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Blog' or . = 'Blog')]</value>
      <webElementGuid>4c2f0d84-c851-44de-89d2-e43c95c63f68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
