<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Czartery</name>
   <tag></tag>
   <elementGuidId>30500739-8510-469e-9e2d-035a158079bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainHeader']/div/div/header/nav/div[4]/a/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>482dadcf-6db8-4180-b8c8-6acda7cd335a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktop__kategoria-text</value>
      <webElementGuid>87c40867-5bbc-4098-8488-7a62f298b672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Czartery</value>
      <webElementGuid>44a1991f-a9e5-4ecc-954a-7647500a585d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainHeader&quot;)/div[@class=&quot;header__desktop&quot;]/div[@class=&quot;desktop__header-position&quot;]/header[@class=&quot;desktop__container-position&quot;]/nav[@class=&quot;desktop__container-kategorie&quot;]/div[4]/a[@class=&quot;desktop__kategorie_siteMap__link&quot;]/div[@class=&quot;desktop__kategoria-wrapper&quot;]/span[@class=&quot;desktop__kategoria-text&quot;]</value>
      <webElementGuid>3c787cb7-6c76-43a8-bbef-a350105b1a95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainHeader']/div/div/header/nav/div[4]/a/div/span</value>
      <webElementGuid>a8314dbc-b237-4f2b-aafc-dcad960a4ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Minute'])[1]/following::span[1]</value>
      <webElementGuid>21fd94fc-b156-467a-9c6c-1ca73e9848de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Końcóweczka'])[1]/following::span[2]</value>
      <webElementGuid>f0057355-c085-403a-9e95-e9ee9d8caf04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wycieczki fakultatywne'])[2]/preceding::span[1]</value>
      <webElementGuid>227ff2fa-67e7-429d-97db-d638d4eace0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog'])[1]/preceding::span[2]</value>
      <webElementGuid>3fd240d2-92b5-4a49-904c-144c4c49fef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Czartery']/parent::*</value>
      <webElementGuid>8dda7a09-5505-423b-bbbb-fb61728b4fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/div/span</value>
      <webElementGuid>4c5cb58f-f786-42b5-b78c-b427f7615a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Czartery' or . = 'Czartery')]</value>
      <webElementGuid>e8567de1-237a-4759-9521-d41b7fe4111d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
